### ISSUE TITLE
Ime repozitorija

### ISSUE THREAD

**Issue by jaanos** [pavlanovak/Consecutive-square-covering#1]
@pavlanovak, svetujem, da ima repozitorij bolj pomenljivo ime, npr. `Consecutive-square-covering`. Ime spremeniš tako, da zgoraj klikneš na *Settings*, nato pa spremeniš ime pod **Repository name**.

Mimogrede, ne pozabita dodati povezave do repozitorija na wiki na spletni učilnici.

**Comment by pavlanovak** [comment]
Sem popravila in dodala povezavo. Hvala.
